version: '3.8'

networks:
    default:
        external: true
        name: ${COMPOSE_PROJECT_NAME}

volumes:
    redis:
        name: redis
        external: true
    cache:
        name: cache
        external: true
    logs:
        name: logs
        external: true

services:
    db:
        image: 'jc21/mariadb-aria:latest'
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}-db
        environment:
            MYSQL_ROOT_PASSWORD: 'npm'
            MYSQL_DATABASE: 'npm'
            MYSQL_USER: 'npm'
            MYSQL_PASSWORD: 'npm'
        volumes:
            - ./data/mysql:/var/lib/mysql

    redis:
        image: redis:latest
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        command: --loglevel verbose
        ports:
            - "${REDIS_PORT_HOST}:6379"
        volumes:
            - redis:/data

    redis-admin:
        image: onlinesolutions/php-micro
        build:
            context: .
            dockerfile: ./php-micro/Dockerfile
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}-redis-admin
        environment:
            - HTTP_DIR=.
            - REDIS_1_HOST=${COMPOSE_PROJECT_NAME}-redis
            - REDIS_1_PORT=6379
        ports:
            - "${REDIS_ADMIN_PORT_HOST}:8080"
        volumes:
            - ./phpRedisAdmin:/var/www/html
            - cache:/var/www/cache
            - logs:/var/logs/app

    proxy:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: always
        ports:
            - '80:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
            - '81:81' # Admin Web Port
        environment:
            DB_MYSQL_HOST: "db"
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: "npm"
            DB_MYSQL_PASSWORD: "npm"
            DB_MYSQL_NAME: "npm"
            DISABLE_IPV6: 'true'
            X_FRAME_OPTIONS: "sameorigin"
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        depends_on:
            - db
