version: '3.8'

networks:
    default:
        external: true
        name: ${COMPOSE_PROJECT_NAME}

volumes:
    redis:
        name: redis
        driver: ${VOLUMES_DRIVER}
    letsencrypt:
        name: letsencrypt
        driver: ${VOLUMES_DRIVER}
    cache:
        name: cache
        driver: ${VOLUMES_DRIVER}
    logs:
        name: logs
        driver: ${VOLUMES_DRIVER}

services:
    redis:
        image: redis:latest
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        command: --loglevel verbose
        ports:
            - "${REDIS_PORT_HOST}:6379"
        volumes:
            - redis:/data

    redis-admin:
        image: onlinesolutions/php-micro
        build:
            context: .
            dockerfile: ./php-micro/Dockerfile
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}-redis-admin
        environment:
            - HTTP_DIR=.
            - REDIS_1_HOST=${COMPOSE_PROJECT_NAME}-redis
            - REDIS_1_PORT=6379
        ports:
            - "${REDIS_ADMIN_PORT_HOST}:8080"
        volumes:
            - ../phpRedisAdmin:/var/www/html
            - cache:/var/www/cache
            - logs:/var/logs/app

    proxy:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: always
        container_name: ${COMPOSE_PROJECT_NAME}-proxy
        ports:
            # Public HTTP Port:
            - '80:80'
            # Public HTTPS Port:
            - '443:443'
            # Admin Web Port:
            - '${PROXY_ADMIN_PORT_HOST}:81'
        environment:
            DB_MYSQL_HOST: ${DB_HOST}
            DB_MYSQL_PORT: ${DB_PORT}
            DB_MYSQL_USER: ${DB_USERNAME}
            DB_MYSQL_PASSWORD: ${DB_PASSWORD}
            DB_MYSQL_NAME: ${DB_DATABASE}
            # Uncomment this if IPv6 is not enabled on your host
            DISABLE_IPV6: 'true'
        volumes:
            - letsencrypt:/etc/letsencrypt
